#!/bin/bash
#get admin config settings for dlink web server
function usage 
{
  echo "Usage: $(basename "$0") -i ip -k keyword [-f configfile]"
  exit 1 
}

configfile=~/.config/dtools/admin.conf

while getopts k:i:f: opt; do
    case $opt in
        i) ip=$OPTARG ;;
        k) k=$OPTARG ;;
        f) configfile=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

while read -r keyword user ipaddress value rest; do
  [[ $keyword == $k && $ipaddress == $ip ]] && echo "$value"
done < "$configfile"