#!/bin/bash
function usage 
{
  echo "Usage: $(basename "$0") -i ip"
  exit 1 
}

while getopts i: opt; do
    case $opt in
        i) ip=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

dconfig -k directory -i "$ip"