#!/bin/bash
# Simple histogram of moving time in seconds between start and end time
function usage 
{
  echo "Usage: $(basename "$0") -i ip -a starttime -b stoptime"
  echo "    -m n moving sec"
  echo "    -m c moving sec comma separated "
  echo "    -d disable histogram"
  echo "    timeformat : (yyyy-mm-dd hh:mm:ss)"
  exit 1 
}

while getopts a:b:dm:i: opt; do
    case $opt in
        i) ip=$OPTARG 
        ;;
        m) movingopt=$OPTARG
        ;;
        d) disablehistopt=1
        ;;
        a) start=$OPTARG
        ;;
        b) stop=$OPTARG
        ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"


moving=
totalsec=0
#Format : 1516496264000,36 01:57:44 346

 while IFS=, read -r t sec rest; do 
     [[ -z $sec ]] && continue
    read -r s rest <<< "$sec"
    (( totalsec+="$s" ))
    moving+=$(printf "%2d" "$s")$'\n'
    [[ $movingopt == 'c' ]] && comma+=$s','
 done < <(dmove -i "$ip" -a "$start" -b "$stop" -t 0) 

comma=${comma%,}
moving=${moving%$'\n'} # remove \n at end

[[ $movingopt == 'n' ]] &&  echo -e "$moving"
[[ $movingopt == 'c' ]] && echo -e "\n$comma"
   
if [[ ! -z $moving && $disablehistopt != '1' ]]; then
  sort -n <<< "$moving" | uniq -c 
fi

dsectohhmm $totalsec