#!/bin/bash

[[ $@ =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] && ip=${BASH_REMATCH[0]}

if [ -z "$ip" ]; then
  printf "Usage: %s [-m] ip\n\t-m motion detection only\n" "$(basename "$0")"
  exit
fi

[[ $@ =~ "-m" ]] && motionopt=${BASH_REMATCH[0]}
#motionopt=$(grep -oE "\-m" <<< "$@")

ping -c 1 "$ip" || exit $?

server=$(dserver "$ip")

case $server in

  Embedthis-Appweb*)

    [[ ! -z "$motionopt" ]] && pipequery="| grep -E 'Event.*motion'"
    eval dreq "http://$ip/cgi-bin/exportlog.cgi" $pipequery
     ;;

  dcs-lig-httpd*)

    [[ ! -z "$motionopt" ]] && pipequery="| grep -E 'Motion.*SD Card is OK'"
     eval dreq --data 'export=true' "http://$ip/eng/admin/export_log.cgi" $pipequery
     ;;

  *)

     echo -e "$(basename $0): Server $server not supported"
     exit 1
     ;;   
esac