#!/bin/bash

function usage 
{
  printf "Usage: %s [-m] -i ip\n\t-m motion detection only\n" "$(basename "$0")"
  exit 1 
}

while getopts mi: opt; do
    case $opt in
        m) motionopt=1 ;;
        i) ip=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

server=$(dserver "$ip")

case $server in

  Embedthis-Appweb*)

    [[ ! -z "$motionopt" ]] && pipequery="| grep -E 'Event.*motion'"
    eval dreq "http://$ip/cgi-bin/exportlog.cgi" $pipequery
     ;;

  dcs-lig-httpd*)

    [[ ! -z "$motionopt" ]] && pipequery="| grep -E 'Motion.*SD Card is OK'"
     eval dreq --data 'export=true' "http://$ip/eng/admin/export_log.cgi" $pipequery
     ;;

  *)

     echo -e "$(basename $0): Server $server not supported"
     exit 1
     ;;   
esac