#!/bin/bash
#get admin password for dlink web server
function usage 
{
  echo "Usage: $(basename "$0") -i ip"
  exit 1 
}

while getopts i: opt; do
    case $opt in
        i) ip=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

grep "$ip" ~/.config/dtools/admin.conf | cut -d' ' -f3