#!/bin/bash
#ping camera as specific intervals

function usage 
{
  echo "Usage: $(basename "$0") -i ip - t [interval]"
  exit 1 
}

while getopts t:i: opt; do
    case $opt in
        i) ip=$OPTARG 
        ;;
        t) interval=$OPTARG
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

if [ -z "$interval" ]; then
  interval=30
fi;

while read -r pong; do
  if [[ $pong != *"PING"* ]]; then 
     echo "$(date +'%F %T'): $pong" ;
 fi;
done < <(ping -i $interval -D "$ip")
