#!/bin/bash

function usage 
{
  echo "Usage: $(basename "$0") -i ip"
  exit 1 
}

while getopts i: opt; do
    case $opt in
        i) ip=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

server=$(dserver -i "$ip")

if [[ -z $server ]]; then
   echo "Failed to get server for ip $ip"
   exit 1;
fi

read -r Y m d H M < <(date -d'1 hours ago' +'%Y %m %d %H %M')

case $server in
   
   Embedthis-Appweb*)

      dcp -i "$ip" "/video/$Y$m$d/$H"
   ;;

   dcs-lig-httpd*)

      dcp -i "$ip" "$Y$m$d/$H"

      ;;

   *)

   echo -e "Server not supported $server"
   ;;
esac
