#!/bin/bash

function usage 
{
  echo "Usage: $(basename "$0") -i ip [-d]"
  echo -e "\t-d - argument to date -d option, default 1 hours ago)\n"
  exit 1 
}

while getopts d:i: opt; do
    case $opt in
        i) ip=$OPTARG 
        ;;
        d) dopt=$OPTARG
        ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

server=$(dserver -i "$ip")

if [[ -z $server ]]; then
   echo "Failed to get server for ip $ip"
   exit 1;
fi

[[ -z $dopt  ]] && dopt='1 hours ago'


read -r Y m d H M < <(date -d"$dopt" +'%Y %m %d %H %M')
exit_status=$?
if (( exit_status  )) ; then
  exit $exit_status
fi

case $server in
   
   Embedthis-Appweb*)

    dcp -i "$ip" "/video/$Y$m$d/$H"
   ;;

   dcs-lig-httpd*)

      dcp -i "$ip" "$Y$m$d/$H"

      ;;

   *)

   echo -e "Server not supported $server"
   ;;
esac
