#!/bin/bash
#get dlink web server from Server http response header

function usage 
{
  echo "Usage: $(basename "$0") -i ip"
  exit 1 
}

while getopts i: opt; do
    case $opt in
        i) ip=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

# Use Server-field in http response?
# Server: dcs-lig-httpd               DCS-936L
# Server: Embedthis-Appweb/3.3.1      DCS-2530L
curl --head "$ip" --silent  2>&1 | while IFS=':' read -r k v; do [[ $k == Server ]] && { echo "${v# }"; break; } done
