#!/bin/bash
#get dlink web server from Server http response header

function usage 
{
  echo "Usage: $(basename "$0") -v -i ip"
  exit 1 
}

while getopts vi: opt; do
    case $opt in
        i) ip=$OPTARG ;;
        v) verbose="-v" ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

# Use Server-field in http response
# Server: dcs-lig-httpd               DCS-936L
# Server: Embedthis-Appweb/3.3.1      DCS-2530L

serverhead=$(curl $verbose --head "$ip" --silent)

curlexit=$?
if [[ $curlexit != 0 ]]; then
   exit $curlexit
fi

if [[ ! -z "$verbose" ]]; then
    echo "$serverhead"
fi

while IFS=':' read -r k v; do
    [[ $k == Server ]] && { echo "${v# }"; break; }
done <<< "$serverhead"

