#!/bin/bash

function usage 
{
  echo "Usage: $(basename "$0") -c command [-d dtools directory -s service -i ip] "
  echo -e "Options:\n\t-c start|stop|enable|disable|wants - service/timer\n\t-s dping|dpoll|drec - ping, polling or recording\n\t-i ip address"
  exit 1 
}

while getopts c:d:s:i: opt; do
    case $opt in
        d) dir=$OPTARG ;;
        c) command=$OPTARG ;;
        i) ip=$OPTARG ;;
        s) service=$OPTARG ;;
    esac
done

[[  -z "$command" ]] && usage

shift "$((OPTIND-1))"

case $command in
  enable)
  
      systemctl --user link "$dir/dpoll@.timer" "$dir/dpoll@.service" "$dir/drec@.timer" "$dir/drec@.service" "$dir/dping@.service" 
      
      case $service in
         dping)
           systemctl --user enable "$service@$ip.service"
           ;;
        dpoll|drec)
           systemctl --user enable "$service@$ip".{timer,service}
           ;;
        esac
      
      
      ;;

  disable)
    systemctl --user disable "dpoll@.timer" "dpoll@.service" "drec@.timer" "drec@.service" "dping@.service" 
      ;;
    
  start)

        case $service in
            dping)
            
            systemctl --user start "$service@$ip.service"
            systemctl --user --no-pager status "$service@$ip.service"
            ;;
            
            dpoll|drec)

            systemctl --user start "$service@$ip.timer"
            systemctl --user --no-pager status "$service@$ip."{timer,service}
            ;;
            
            *)
            echo "$service@$ip not supported"
            ;;
        esac

     ;;

    stop)

       case $service in
         dping)
           systemctl --user stop "$service@$ip.service"
           
           ;;
        dpoll|drec)
           systemctl --user stop "$service@$ip".{timer,service}
           ;;
        esac
    ;;

    status)

       systemctl --user status dpoll@*.timer dping@*.service drec@*.timer
       ;;

    wants)

     case $service in
            dping)
            
           systemctl --user add-wants default.target "$service@$ip.service"
            ;;
            
            dpoll|drec)

            
            systemctl --user add-wants default.target "$service@$ip.timer"
            
            ;;
            
            *)
            echo "$service@$ip not supported"
            ;;
        esac

     ;;

      
    *)
    echo "Unknown command $command"
esac
#systemctl --user enable dpoll@.timer drec@.timer dping@.service "$dir/dtools.target"
#systemctl --user daemon-reload
#systemctl --user start rsl.timer gsl.timer psl.service
#systemctl --user status {drec*,dpoll*,dping*}.{timer,service}