#!/bin/bash

function usage 
{
  echo "Usage: $(basename "$0") -i ip"
  exit 1 
}

while getopts i: opt; do
    case $opt in
        i) ip=$OPTARG ;;
    esac
done

[[ -z "$ip" ]] && usage

shift "$((OPTIND-1))"

#dateformat: "2018-01-09 22:50:00"
start=$(($(date -d"$1" +%s) * 1000));
stop=$(($(date -d"$2" +%s) * 1000))

threshold=$3
[[ -z $threshold ]] && threshold=10

sum=0;

while read -r startms stopms startdate starttime stoptime sec cumsec; do 
    if (( $startms >= $start && $startms <= $stop )); then 
      (( sum+=$sec ));
      (( $sec > $threshold )) && echo "$startms,$sec $starttime $sum"; 
    fi; 
done < <(dm -i "$ip")

hours=$((sum / 60))
minutes=$(( sum - hours * 60 ))

printf "%d %02d:%02d\n" $sum $hours $minutes 
