#!/bin/bash
systemctl --user link "$HOME/.local/bin/gsl@.timer" "$HOME/.local/bin/gsl@.service" "$HOME/.local/bin/rsl@.timer" "$HOME/.local/bin/rsl@.service" "$HOME/.local/bin/psl@.service"
systemctl --user enable gsl@.timer rsl@.timer psl@.service "$HOME/.local/bin/sleep.target"
systemctl --user daemon-reload
#systemctl --user start rsl.timer gsl.timer psl.service
#systemctl --user status {r,g,p}sl.{timer,service}