#!/bin/bash
# Strips off Author section from Polar TCX export, thats somewhat incompatible with current garmin connect import

if [ ! -f "$1" ]; then
  pwd
  echo "$1" does not exists
  exit 1
fi

#echo "$1" Removing XML-element Author for compatibility with Garmin Connect manual import
# Only author-tag cutoff=316
tcxfile=$(cat "$1")
num_track=$(grep -mw Track <(echo "$tcxfile"))
echo "$(head -c - "$1")</TrainingCenterDatabase>" > "$1"