#!/bin/bash
#Uses camera syslog to get mp4 files
#Known issues: will not get files if the log is cleared, i.e after reboot of camera
#set -x 
#trap read debug

verbose="-v"

if [ -z "$1" ]; then
  echo "Usage: gsl ip"
  exit 1
fi

[[ $@ =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] && ip=${BASH_REMATCH[0]}
ping -c 1 "$ip" || exit $?

function getSDFile-Embedthis-Appweb
{
  #set 100 files pr page
  #curl 'http://192.168.0.106/cgi-bin/sdoperate.cgi?sdfpp=3&del=' 
  #cd into /video/20180103/00 page 1
  #curl 'http://192.168.0.106/cgi-bin/sdoperate.cgi?list=&path=/video/20180103/00&page=1'
  #ls *.mp4
  #curl 'http://192.168.0.106/setup_sdlist.htm'
  # grep inside embedded <script> for g_filelistStr
  #then setup_sdlist.htm | grep '^var g_filelistStr = decode.*' | grep -o "p1[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9].mp4"
  # grep for totalpages
  # | grep '^var g_totalpage' | cut -d'"' -f2
  local prefix='p1_'
  local mlog=$(mlog "$ip")
  for log in "$mlog"; do
    read -r date time $log
  done

  dlink_getSDFile=http://$ip/cgi-bin/sddownload.cgi
     #http://192.168.0.106/cgi-bin/sddownload.cgi?file=/video/20180103/00/p120180103_003150.mp4

    


  return
}

function getSDFile-dcs-lig-httpd
{
  dlink_getSDFile=http://$ip/cgi/admin/getSDFile.cgi
    #mlog output format: 2017-12-28 07:11:10 Recording 20171228_071100.mp4 by Motion Detection to SD Card is OK.
    # shellcheck disable=2086
    mp4_videos=$(mlog $ip | cut -d' ' -f4)

    for filename in $mp4_videos; do 

      path=$serial/${filename:0:8}/${filename:9:2}/$filename
      
      if [ ! -f "$filename" ]; then 
        urls+="$dlink_getSDFile?file=$filename&path=$path "
      #else
      # echo "$filename already downloaded"; 
      fi

    done
}

#read -r viddir serial camname < <(sdir "$ip")
server=$(dserver "$ip")
guess_viddir=$(grep -m 1 Video <(ls -d "$HOME"/*/))
viddir="$guess_viddir/camera-$ip"
cd "$viddir" || { echo "Failed to cd into $viddir"; if [ ! -d "$viddir" ]; then mkdir -v  "$viddir"; cd "$viddir" || { echo "Failed to cd into $viddir, using $PWD"; viddir=$PWD; } fi }

# Max. command line size bash; getconf ARG_MAX
#https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit

curlopt="-u admin:$(dpassw "$ip") --anyauth -s --compressed -e http://$ip/"

# log-format DCS-2530: 2018/01/02 14:02:26 Event trigger - motion detection.

case $server in
   Embedthis-Appweb*)
     getSDFile-Embedthis-Appweb
     ;;
    dcs-lig-httpd*)
      getSDFile-dcs-lig-httpd
      ;;
esac

if [ ${#urls} -gt 0 ]; then 
  echo "Fetching video from camera at $ip"
  # shellcheck disable=2086
  curl $curlopt -J  $verbose --remote-name-all $urls
else  
  echo "No new videos, skipping download"
fi

cd - >/dev/null || exit
