#!/bin/bash
#Uses camera SD log to get mp4 files from camera
#Known issues: will not get files if the log is cleared, i.e after reboot of camera
#set -x 
#trap read debug

verbose="-v"

if [ -z "$1" ]; then
  echo "Usage: gsl ipadr"
  exit 1
fi

ipadr=$1
read -r camuniq serial camname <<< $(sdir "$ipadr")
guess_viddir=$(ls -d "$HOME"/*/ | grep -m 1 Video)
viddir=$guess_viddir$camuniq
camlog="$guess_viddir$camuniq/camera.log"
cd "$viddir" || { echo "Failed to cd into $viddir"; if [ ! -d "$viddir" ]; then mkdir -v  "$viddir"; cd "$viddir" || { echo "Failed to cd into $viddir, using $PWD"; viddir=$PWD; } fi }

# Max. command line size bash; getconf ARG_MAX
#https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit

echo "Log $serial camera $camname at $ipadr -> $camlog"
echo "Video directory $serial camera $camname at $ipadr -> $viddir"
curlopt="-u admin: --anyauth -s --compressed -e http://$ipadr/"

# shellcheck disable=2086
motionlog=$(curl $curlopt --data 'export=true'  "http://$ipadr/eng/admin/export_log.cgi" | tee "$camlog"  | grep -E "Motion.*SD Card is OK" | cut -d' ' -f4)

for filename in $motionlog; do 

  path=$serial/${filename:0:8}/${filename:9:2}/$filename
  
  if [ ! -f "$filename" ]; then 
    urls+="http://$ipadr/cgi/admin/getSDFile.cgi?file=$filename&path=$path "
  #else
  # echo "$filename already downloaded"; 
  fi

done

if [ ${#urls} -gt 0 ]; then 
  echo "Fetching video from camera at $ipadr"
  # shellcheck disable=2086
  curl $curlopt -J  $verbose --remote-name-all $urls
else  
  echo "No new videos, skipping download"
fi

cd - >/dev/null || exit
