#!/bin/bash
#Uses camera SD log to get mp4 files from camera
#Known issues: will not get files if the log is cleared, i.e after reboot of camera
#set -x 
#trap read debug

verbose="-v"

if [ -z "$1" ]; then
  echo "Usage: gsl ipadr"
  exit 1
fi

ipadr=$1
ping -c 1 "$ipadr" || exit $?

read -r viddir serial camname < <(sdir "$ipadr")
camlog="$viddir/camera.log"
cd "$viddir" || { echo "Failed to cd into $viddir"; if [ ! -d "$viddir" ]; then mkdir -v  "$viddir"; cd "$viddir" || { echo "Failed to cd into $viddir, using $PWD"; viddir=$PWD; } fi }

# Max. command line size bash; getconf ARG_MAX
#https://stackoverflow.com/questions/19354870/bash-command-line-and-input-limit

echo "Log $serial camera $camname at $ipadr -> $camlog"
echo "Video directory $serial camera $camname at $ipadr -> $viddir"
curlopt="-u admin: --anyauth -s --compressed -e http://$ipadr/"

case $serial in
   DCS-936L)
     dlink_getSDFile=http://$ipadr/cgi/admin/getSDFile.cgi
     ;;
    *)
    dlink_getSDFile=http://$ipadr/cgi/admin/getSDFile.cgi

esac

#mlog output format: 2017-12-28 07:11:10 Recording 20171228_071100.mp4 by Motion Detection to SD Card is OK.
# shellcheck disable=2086
mp4_videos=$(mlog $ipadr | cut -d' ' -f4)

for filename in $mp4_videos; do 

  path=$serial/${filename:0:8}/${filename:9:2}/$filename
  
  if [ ! -f "$filename" ]; then 
    urls+="$dlink_getSDFile?file=$filename&path=$path "
  #else
  # echo "$filename already downloaded"; 
  fi

done

if [ ${#urls} -gt 0 ]; then 
  echo "Fetching video from camera at $ipadr"
  # shellcheck disable=2086
  curl $curlopt -J  $verbose --remote-name-all $urls
else  
  echo "No new videos, skipping download"
fi

cd - >/dev/null || exit
