#!/bin/bash
#ping camera as specific intervals
interval=60
ipadr=$1

if [ -z "$1" ]; then
  echo "Usage: psl ipadr {interval}"
  exit 1
fi;

ping -i $interval -D "$ipadr" | while read -r pong; do if [[ $pong != *"PING"* ]]; then echo "$(date +'%F %T'): $pong" ; fi; done
