#!/bin/bash
#ping camera as specific intervals and log echo response
INTERVAL=60
IPCAM=$1

if [ -z $1 ]; then
  IPCAM=192.168.0.110
fi;


DEVSTAT=$(curl --anyauth -u admin:  -s  "http://$IPCAM/eng/admin/st_device.cgi" -e "http://$IPCAM")
#Serial (used as directory) should be next level from root directory on camera SD card, otherwise access problems will occur "501 not implemented" response
SERIAL=$(echo $DEVSTAT | tr ' ' '\n' | grep -m 1 serial | cut -d ">" -f 2 | cut -d "<" -f 1)
CAMERANAME=$(echo $DEVSTAT | tr ' ' '\n' | grep -m 1 cameraName | cut -d ">" -f 2 | cut -d "<" -f 1)


PINGLOG="$HOME/Nedlastinger/ping-$CAMERANAME-$SERIAL-$IPCAM.log"

echo "Ping $CAMERANAME $SERIAL at $IPCAM each $INTERVAL sec -> $PINGLOG"

if (( $(stat -c %s $PINGLOG) > 10000000 )); then
  rm -v $PINGLOG
fi
ping -i $INTERVAL -D $IPCAM | while read pong; do if [[ $pong != *"PING"* ]]; then echo "$(date +'%F %T'): $pong" | tee -a $PINGLOG ; fi; done
