#!/bin/bash
LENGTH=$1
FILEBASE=$2
STREAM=$3
#IFPS=$4
OFPS=$4
IPCAM=$5
OUTDIR=/home/henning/Videoklipp/sleeplab
if [ "$1" == "-h" ]; then
   echo "Arguments : LENGTH (10=10sec,08:00:00 8hours) FILEBASE (without extension) STREAM  (1/2/3)  output FPS  IPCAM (def 192.168.0.110) "
   exit 0
fi
if [ -z "$1" ]; then
  LENGTH=09:00:00
fi
if [ -z "$2" ]; then
  FILEBASE=sleep
fi
if [ -z "$3" ]; then
  STREAM=1
fi
# Only necessary for raw video files -> probably not applicable for rtsp stream from D-link cam DCS-936L
#if [ -z "$4" ]; then
#  IFPS=10
#fi
if [ -z "$4" ]; then
  OFPS=30
fi

if [ -z "$5" ]; then
  IPCAM=192.168.0.110
fi
#OUT=~/Videoklipp/sleeplab/$(date +"20%y%m%d")_sleep.mp4

VIDEOFILE=$OUTDIR/$FILEBASE.mp4
MP3FILE=$OUTDIR/$FILEBASE.mp3
RTSP=rtsp://$IPCAM/play$STREAM.sdp
# http://192.168.0.110:80/av2/mjpg.cgi?profileid=3 - workaround for stream 3 DCS-936L firmware v1.5/works in firmware 1.2
AUDIOLEVEL1=-45dB
AUDIOLEVEL2=-35dB
AUDIOLEVEL3=-25dB
AUDIOFILTER="-af silenceremove=0:0:0:-1:1:$AUDIOLEVEL1 $OUTDIR/$(date +"20%y%m%d")_$FILEBASE$AUDIOLEVEL1.mp3 -af silenceremove=0:0:0:-1:1:$AUDIOLEVEL2 $OUTDIR/$(date +"20%y%m%d")_$FILEBASE$AUDIOLEVEL2.mp3 -af silenceremove=0:0:0:-1:1:$AUDIOLEVEL3 $OUTDIR/$(date +"20%y%m%d")_$FILEBASE$AUDIOLEVEL3.mp3"
echo Audio filter: $AUDIOFILTER
echo "Recording $LENGTH from $RTSP to $VIDEOFILE, input FPS $IFPS output FPS $OFPS"
mv -v -f $VIDEOFILE $FILEBASE-backup.mp4
mv -v -f $MP3FILE $FILEBASE-backup.mp3
if [ -z "$OFPS" ]; then
  # Let ffmpeg determine framerates
  ffmpeg -y -t $LENGTH -i $RTSP $VIDEOFILE $MP3FILE $AUDIOFILTER
#  FFREPORT=file=ffmpeg-sleep.log ffmpeg -y -loglevel verbose -t $LENGTH -i $RTSP $VIDEOFILE $MP3FILE $AUDIOFILTER

else
  #Force specific output framerate
  ffmpeg -y -t $LENGTH -i $RTSP -r $OFPS $VIDEOFILE $MP3FILE $AUDIOFILTER
fi

echo "FFMPEG/RSL script exit statsus " $?
