#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: $(basename "$0") url"
  exit 1
fi

[[ $@ =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] && ip=${BASH_REMATCH[0]}

curlopt="--user admin:$(dpassw -i "$ip") --anyauth --silent --compressed --referer http://$ip/"

curl $curlopt $@


