#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: sstat ip"
  exit
else
  [[ $@ =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] && ip=${BASH_REMATCH[0]}
fi

ping -c 1 "$ip" >/dev/null  || exit $?

curlopt="-u admin:$(dpassw -i "$ip") --anyauth -s --compressed -e http://$ip/"

# shellcheck disable=2086
curl $curlopt  "http://$ip/eng/admin/st_device.cgi"